// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srmwcrsdqbvrvtvmhutm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNybXdjcnNkcWJ2cnZ0dm1odXRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTI4MDAsImV4cCI6MjA2MDc4ODgwMH0.cvKCdDpbNI1L_1khVG0KGlPNO7-T7i0wpOBIhAR24R4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);